version: '3'

services:
  starter.api:
    container_name: starter.api
    image: starter.api:latest
    ports:
      - 8080:80
      - 8443:443

  starter.messageconsumer.console:
    container_name: starter.messageconsumer.console
    image: starter.messageconsumer.console:latest